In [5]:
def parse_board(board):
    return np.array([[int(c) if c.isdigit() else 0 for c in row.strip() if c != " "] for row in board.strip().split('\n')])

def print_board(board):
    for i, row in enumerate(board):
        if i % 3 == 0 and i != 0:
            print("- - - - - - - - - - - -")
        for j, val in enumerate(row):
            if j % 3 == 0 and j != 0:
                print("|", end=" ")
            if j == 8:
                print(val)
            else:
                print(str(val) + " ", end="")
    print()

def board_is_solved(board):

    # Check rows
    for num in range(1, 10):
        for i in range(9):
            count = 0
            for j in range(9): #cycle through columns of a fixed row
                if board[i][j] == num:
                    count += 1
                if count > 1: #if a number appear more than once in a row
                    return False
            if count < 1: #if a number doesn't appear in a row
                return False
                    
    # check columns
    for num in range(1, 10):
        for j in range(9):
            count = 0
            for i in range(9): #cycle through rows of a fixed column
                if board[i][j] == num:
                    count += 1
                if count > 1: #if a number appear more than once in a row
                    return False
            if count < 1: #if a number doesn't appear in a row
                return False

    # Check boxes
    for num in range(1, 10):
        for box_x in range(1, 3):
            for box_y in range(1, 3):
                count = 0
                for i in range(box_y * 3, box_y * 3 + 3):
                    for j in range(box_x * 3, box_x * 3 + 3):
                        if board[i][j] == num:
                            count += 1
                        if(count > 1): #if a number appears more than one time in a box 3x3
                            return False
                if count < 1: #if a number doesn't appear in a box
                    return False
    return True

In [ ]:
def get_first_free_pos(board):
    
    for x in range(9):
        for y in range(9):
            if board[x][y] == 0:
                return (x,y)
    
    return None

def get_valid_num_in_position(board, pos):
    
    list = c(1,2,3,4,5,6,7,8,9)
    #check row
    
    
    return list
    

In [1]:
import numpy as np
from scipy.optimize import minimize

def create_initial_x(board):
    x = np.zeros((9, 9, 9))
    for i in range(9):
        for j in range(9):
            if board[i, j] != 0:
                x[i, j, board[i, j] - 1] = 1 # nella board in z = 3-1 ad esempio ci saranno tutte le posizioni in cui c'era inizialmente un 3 segnato a 1
            else:
                x[i, j, :] = 1/9
    return x.flatten()

def objective(x):
    return 0

def constraint_sum_to_one(x):
    x = x.reshape((9, 9, 9))
    return np.sum(x, axis=2).flatten() - 1

def constraint_row(x):
    x = x.reshape((9, 9, 9))
    return np.sum(x, axis=1).flatten() - 1

def constraint_col(x):
    x = x.reshape((9, 9, 9))
    return np.sum(x, axis=0).flatten() - 1

def constraint_box(x):
    x = x.reshape((9, 9, 9))
    constraints = []
    for i in range(0, 9, 3):
        for j in range(0, 9, 3):
            box = x[i:i+3, j:j+3, :]
            constraints.extend(np.sum(box, axis=(0, 1)) - 1)
    return np.array(constraints)

def constraint_fixed(x, board):
    x = x.reshape((9, 9, 9))
    constraints = []
    for i in range(9):
        for j in range(9):
            if board[i, j] != 0:
                constraints.append(x[i, j, board[i, j] - 1] - 1)
    return np.array(constraints)

def project_simplex(y):
    u = np.sort(y)[::-1]
    cssv = np.cumsum(u) - 1
    ind = np.arange(len(y)) + 1
    cond = u - cssv / ind > 0
    rho = ind[cond][-1]
    theta = cssv[cond][-1] / float(rho)
    w = np.maximum(y - theta, 0)
    return w

def project(x):
    x = x.reshape((9, 9, 9))
    for i in range(9):
        for j in range(9):
            x[i, j] = project_simplex(x[i, j])
    return x.flatten()

def solve_sudoku(board):
    initial_x = create_initial_x(board)
    print("obrobrio:")
    print_board(initial_x)
    constraints = [
        {'type': 'eq', 'fun': constraint_sum_to_one},
        {'type': 'eq', 'fun': constraint_row},
        {'type': 'eq', 'fun': constraint_col},
        {'type': 'eq', 'fun': constraint_box},
        {'type': 'eq', 'fun': lambda x: constraint_fixed(x, board)}
    ]
    
    bounds = [(0, 1) for _ in range(9*9*9)]
    
    result = minimize(
        objective,
        initial_x,
        method='SLSQP',
        constraints=constraints,
        bounds=bounds,
        options={'maxiter': 1000, 'ftol': 1e-8}
    )
    
    solution = result.x.reshape((9, 9, 9))
    return np.argmax(solution, axis=2) + 1

# Esempio di utilizzo
sudoku_board = """
37. 5.. ..6
... 36. .12
... .91 75.
... 154 .7.
..3 .7. 6..
.5. 638 ...
.64 98. ...
59. .26 ...
2.. ..5 .64
"""

board = parse_board(sudoku_board)
print("Sudoku iniziale:")
print_board(board)

solved_board = solve_sudoku(board)
print("\nSoluzione:")
print_board(solved_board)

print("La soluzione trovata è corretta:", board_is_solved(solved_board))

NameError: name 'parse_board' is not defined

In [3]:
import numpy as np
from scipy.optimize import minimize

def create_initial_x(board):
    x = np.zeros((9, 9, 9))
    for i in range(9):
        for j in range(9):
            if board[i, j] != 0:
                x[i, j, board[i, j] - 1] = 1
            else:
                x[i, j, :] = 1/9
    return x.flatten()

def objective(x):
    return 0

def constraint_sum_to_one(x):
    x = x.reshape((9, 9, 9))
    return np.sum(x, axis=2).flatten() - 1

def constraint_row(x):
    x = x.reshape((9, 9, 9))
    return np.sum(x, axis=1).flatten() - 1

def constraint_col(x):
    x = x.reshape((9, 9, 9))
    return np.sum(x, axis=0).flatten() - 1

def constraint_box(x):
    x = x.reshape((9, 9, 9))
    constraints = []
    for i in range(0, 9, 3):
        for j in range(0, 9, 3):
            box = x[i:i+3, j:j+3, :]
            constraints.extend(np.sum(box, axis=(0, 1)) - 1)
    return np.array(constraints)

def constraint_fixed(x, board):
    x = x.reshape((9, 9, 9))
    constraints = []
    for i in range(9):
        for j in range(9):
            if board[i, j] != 0:
                constraints.append(x[i, j, board[i, j] - 1] - 1)
    return np.array(constraints)

def project_simplex(y):
    u = np.sort(y)[::-1]
    cssv = np.cumsum(u) - 1
    ind = np.arange(len(y)) + 1
    cond = u - cssv / ind > 0
    rho = ind[cond][-1]
    theta = cssv[cond][-1] / float(rho)
    w = np.maximum(y - theta, 0)
    return w

def project(x):
    x = x.reshape((9, 9, 9))
    for i in range(9):
        for j in range(9):
            x[i, j] = project_simplex(x[i, j])
    return x.flatten()

def solve_sudoku(board):
    initial_x = create_initial_x(board)
    
    constraints = [
        {'type': 'eq', 'fun': constraint_sum_to_one},
        {'type': 'eq', 'fun': constraint_row},
        {'type': 'eq', 'fun': constraint_col},
        {'type': 'eq', 'fun': constraint_box},
        {'type': 'eq', 'fun': lambda x: constraint_fixed(x, board)}
    ]
    
    bounds = [(0, 1) for _ in range(9*9*9)]
    
    result = minimize(
        objective,
        initial_x,
        method='SLSQP',
        constraints=constraints,
        bounds=bounds,
        options={'maxiter': 1000, 'ftol': 1e-8}
    )
    
    solution = result.x.reshape((9, 9, 9))
    return np.argmax(solution, axis=2) + 1

# Esempio di utilizzo
sudoku_board = """
37. 5.. ..6
... 36. .12
... .91 75.
... 154 .7.
..3 .7. 6..
.5. 638 ...
.64 98. ...
59. .26 ...
2.. ..5 .64
"""

board = parse_board(sudoku_board)
print("Sudoku iniziale:")
print_board(board)

solved_board = solve_sudoku(board)
print("\nSoluzione:")
print_board(solved_board)

Sudoku iniziale:
3 7 . . 5 . . . . . 6
. . . . 3 6 . . . 1 2
. . . . . 9 1 . 7 5 .
. . . . 1 5 4 . . 7 .
. . 3 . . 7 . . 6 . .
. 5 . . 6 3 8 . . . .
. 6 4 . 9 8 . . . . .
5 9 . . . 2 6 . . . .
2 . . . . . 5 . . 6 4

Soluzione:
3 7 1 1 5 1 1 1 1
1 1 1 1 3 6 1 1 1
1 1 1 1 1 9 1 1 7
1 1 1 1 1 5 4 1 1
1 1 3 1 1 7 1 1 6
1 5 1 1 6 3 8 1 1
1 6 4 1 9 8 1 1 1
5 9 1 1 1 2 6 1 1
2 1 1 1 1 1 5 1 1


In [3]:
import numpy as np
from scipy.optimize import minimize

def parse_board(board):
    return np.array([[int(c) if c.isdigit() else 0 for c in row.strip() if c != " "] for row in board.strip().split('\n')])

def print_board(board):
    for row in board:
        print(' '.join(str(int(x)) if x != 0 else '.' for x in row))

def create_initial_x(board):
    x = np.zeros((9, 9, 9))
    for i in range(9):
        for j in range(9):
            if board[i, j] != 0:
                x[i, j, board[i, j] - 1] = 1
            else:
                x[i, j, :] = 1/9
    return x.flatten()

def objective(x):
    return -np.sum(x**2)  # Encourage more definite assignments

def constraint_sum_to_one(x):
    x = x.reshape((9, 9, 9))
    return np.sum(x, axis=2).flatten() - 1

def constraint_row(x):
    x = x.reshape((9, 9, 9))
    return np.sum(x, axis=1).flatten() - 1

def constraint_col(x):
    x = x.reshape((9, 9, 9))
    return np.sum(x, axis=0).flatten() - 1

def constraint_box(x):
    x = x.reshape((9, 9, 9))
    constraints = []
    for i in range(0, 9, 3):
        for j in range(0, 9, 3):
            box = x[i:i+3, j:j+3, :]
            constraints.extend(np.sum(box, axis=(0, 1)) - 1)
    return np.array(constraints)

def constraint_fixed(x, board):
    x = x.reshape((9, 9, 9))
    constraints = []
    for i in range(9):
        for j in range(9):
            if board[i, j] != 0:
                constraints.append(x[i, j, board[i, j] - 1] - 1)
    return np.array(constraints)

def is_valid(board):
    for i in range(9):
        if len(set(board[i])) != 9 or len(set(board[:, i])) != 9:
            return False
    for i in range(0, 9, 3):
        for j in range(0, 9, 3):
            if len(set(board[i:i+3, j:j+3].flatten())) != 9:
                return False
    return True

def local_search(board, max_iterations=1000):
    for _ in range(max_iterations):
        if is_valid(board):
            return board
        i, j = np.random.randint(0, 9, 2)
        if board[i, j] == 0:
            continue
        possible_values = set(range(1, 10)) - set(board[i]) - set(board[:, j])
        if possible_values:
            board[i, j] = np.random.choice(list(possible_values))
    return board

def solve_sudoku(board):
    initial_x = create_initial_x(board)
    
    constraints = [
        {'type': 'eq', 'fun': constraint_sum_to_one},
        {'type': 'eq', 'fun': constraint_row},
        {'type': 'eq', 'fun': constraint_col},
        {'type': 'eq', 'fun': constraint_box},
        {'type': 'eq', 'fun': lambda x: constraint_fixed(x, board)}
    ]
    
    bounds = [(0, 1) for _ in range(9*9*9)]
    
    result = minimize(
        objective,
        initial_x,
        method='SLSQP',
        constraints=constraints,
        bounds=bounds,
        options={'maxiter': 1000, 'ftol': 1e-8}
    )
    
    solution = result.x.reshape((9, 9, 9))
    initial_solution = np.argmax(solution, axis=2) + 1
    
    # Apply local search to refine the solution
    refined_solution = local_search(initial_solution)
    
    return refined_solution

# Esempio di utilizzo
sudoku_board = """
37. 5.. ..6
... 36. .12
... .91 75.
... 154 .7.
..3 .7. 6..
.5. 638 ...
.64 98. ...
59. .26 ...
2.. ..5 .64
"""

board = parse_board(sudoku_board)
print("Sudoku iniziale:")
print_board(board)

solved_board = solve_sudoku(board)
print("\nSoluzione:")
print_board(solved_board)

print("\nLa soluzione è valida:", is_valid(solved_board))

Sudoku iniziale:
3 7 . 5 . . . . 6
. . . 3 6 . . 1 2
. . . . 9 1 7 5 .
. . . 1 5 4 . 7 .
. . 3 . 7 . 6 . .
. 5 . 6 3 8 . . .
. 6 4 9 8 . . . .
5 9 . . 2 6 . . .
2 . . . . 5 . 6 4

Soluzione:
3 7 6 5 8 4 2 1 9
8 1 5 3 6 7 9 2 4
2 4 3 6 9 1 8 5 7
7 2 1 1 5 8 4 6 3
4 5 9 2 7 3 6 1 8
1 8 2 7 4 9 1 3 5
1 6 8 9 3 2 5 7 1
5 9 7 8 2 6 3 4 1
9 3 1 4 1 5 7 8 2

La soluzione è valida: False


In [5]:
import numpy as np
from scipy.optimize import minimize

def parse_board(board):
    return np.array([[int(c) if c.isdigit() else 0 for c in row.strip()] for row in board.strip().split('\n')])

def print_board(board):
    for row in board:
        print(' '.join(str(int(x)) if x != 0 else '.' for x in row))

def create_initial_x(board):
    x = np.zeros((9, 9, 9))
    for i in range(9):
        for j in range(9):
            if board[i, j] != 0:
                x[i, j, board[i, j] - 1] = 1
            else:
                x[i, j, :] = 1/9
    return x.flatten()

def objective(x):
    return -np.sum(x**2)  # Encourage more definite assignments

def constraint_sum_to_one(x):
    x = x.reshape((9, 9, 9))
    return np.sum(x, axis=2).flatten() - 1

def constraint_row(x):
    x = x.reshape((9, 9, 9))
    return np.sum(x, axis=1).flatten() - 1

def constraint_col(x):
    x = x.reshape((9, 9, 9))
    return np.sum(x, axis=0).flatten() - 1

def constraint_box(x):
    x = x.reshape((9, 9, 9))
    constraints = []
    for i in range(0, 9, 3):
        for j in range(0, 9, 3):
            box = x[i:i+3, j:j+3, :]
            constraints.extend(np.sum(box, axis=(0, 1)) - 1)
    return np.array(constraints)

def constraint_fixed(x, board):
    x = x.reshape((9, 9, 9))
    constraints = []
    for i in range(9):
        for j in range(9):
            if board[i, j] != 0:
                constraints.append(x[i, j, board[i, j] - 1] - 1)
    return np.array(constraints)

def is_valid(board):
    for i in range(9):
        if len(set(board[i])) != 9 or len(set(board[:, i])) != 9:
            return False
    for i in range(0, 9, 3):
        for j in range(0, 9, 3):
            if len(set(board[i:i+3, j:j+3].flatten())) != 9:
                return False
    return True

def find_empty(board):
    for i in range(9):
        for j in range(9):
            if board[i, j] == 0:
                return i, j
    return None

def is_safe(board, num, pos):
    # Check row
    for j in range(9):
        if board[pos[0], j] == num and pos[1] != j:
            return False

    # Check column
    for i in range(9):
        if board[i, pos[1]] == num and pos[0] != i:
            return False

    # Check box
    box_x = pos[1] // 3
    box_y = pos[0] // 3
    for i in range(box_y*3, box_y*3 + 3):
        for j in range(box_x*3, box_x*3 + 3):
            if board[i, j] == num and (i, j) != pos:
                return False

    return True

def solve_backtracking(board):
    find = find_empty(board)
    if not find:
        return True
    else:
        row, col = find

    for num in range(1, 10):
        if is_safe(board, num, (row, col)):
            board[row, col] = num

            if solve_backtracking(board):
                return True

            board[row, col] = 0

    return False

def solve_sudoku(board):
    initial_x = create_initial_x(board)
    
    constraints = [
        {'type': 'eq', 'fun': constraint_sum_to_one},
        {'type': 'eq', 'fun': constraint_row},
        {'type': 'eq', 'fun': constraint_col},
        {'type': 'eq', 'fun': constraint_box},
        {'type': 'eq', 'fun': lambda x: constraint_fixed(x, board)}
    ]
    
    bounds = [(0, 1) for _ in range(9*9*9)]
    
    result = minimize(
        objective,
        initial_x,
        method='SLSQP',
        constraints=constraints,
        bounds=bounds,
        options={'maxiter': 1000, 'ftol': 1e-8}
    )
    
    solution = result.x.reshape((9, 9, 9))
    initial_solution = np.argmax(solution, axis=2) + 1
    
    # Apply backtracking to ensure a valid solution
    solve_backtracking(initial_solution)
    
    return initial_solution

# Esempio di utilizzo
sudoku_board = """
37. 5.. ..6
... 36. .12
... .91 75.
... 154 .7.
..3 .7. 6..
.5. 638 ...
.64 98. ...
59. .26 ...
2.. ..5 .64
"""

board = parse_board(sudoku_board)
print("Sudoku iniziale:")
print_board(board)

solved_board = solve_sudoku(board)
print("\nSoluzione:")
print_board(solved_board)

print("\nLa soluzione è valida:", is_valid(solved_board))

Sudoku iniziale:
3 7 . . 5 . . . . . 6
. . . . 3 6 . . . 1 2
. . . . . 9 1 . 7 5 .
. . . . 1 5 4 . . 7 .
. . 3 . . 7 . . 6 . .
. 5 . . 6 3 8 . . . .
. 6 4 . 9 8 . . . . .
5 9 . . . 2 6 . . . .
2 . . . . . 5 . . 6 4

Soluzione:
3 7 1 1 5 1 1 1 1
1 1 1 1 3 6 1 1 1
1 1 1 1 1 9 1 1 7
1 1 1 1 1 5 4 1 1
1 1 3 1 1 7 1 1 6
1 5 1 1 6 3 8 1 1
1 6 4 1 9 8 1 1 1
5 9 1 1 1 2 6 1 1
2 1 1 1 1 1 5 1 1

La soluzione è valida: False


In [3]:
import numpy as np

def parse_board(board):
    return np.array([[int(c) if c.isdigit() else 0 for c in row.strip() if c != " "] for row in board.strip().split('\n')])

def print_board(board):
    for i, row in enumerate(board):
        if i % 3 == 0 and i != 0:
            print("- - - - - - - - - - - -")
        for j, val in enumerate(row):
            if j % 3 == 0 and j != 0:
                print("|", end=" ")
            if j == 8:
                print(val)
            else:
                print(str(val) + " ", end="")

def find_empty(board):
    for i in range(9):
        for j in range(9):
            if board[i][j] == 0:
                return i, j
    return None

def is_valid(board, num, pos):
    # Check row
    for j in range(9):
        if board[pos[0]][j] == num and pos[1] != j:
            return False

    # Check column
    for i in range(9):
        if board[i][pos[1]] == num and pos[0] != i:
            return False

    # Check box
    box_x = pos[1] // 3
    box_y = pos[0] // 3

    for i in range(box_y * 3, box_y * 3 + 3):
        for j in range(box_x * 3, box_x * 3 + 3):
            if board[i][j] == num and (i, j) != pos:
                return False

    return True

def solve_sudoku(board):
    empty = find_empty(board)
    if not empty:
        return True
    else:
        row, col = empty

    for num in range(1, 10):
        if is_valid(board, num, (row, col)):
            board[row][col] = num

            if solve_sudoku(board):
                return True

            board[row][col] = 0

    return False

def board_is_solved(board):

    # Check rows
    for num in range(1, 10):
        for i in range(9):
            count = 0
            for j in range(9): #cycle through columns of a fixed row
                if board[i][j] == num:
                    count += 1
                if count > 1: #if a number appear more than once in a row
                    return False
            if count < 1: #if a number doesn't appear in a row
                return False
                    
    # check columns
    for num in range(1, 10):
        for j in range(9):
            count = 0
            for i in range(9): #cycle through rows of a fixed column
                if board[i][j] == num:
                    count += 1
                if count > 1: #if a number appear more than once in a row
                    return False
            if count < 1: #if a number doesn't appear in a row
                return False

    # Check boxes
    for num in range(1, 10):
        for box_x in range(1, 3):
            for box_y in range(1, 3):
                count = 0
                for i in range(box_y * 3, box_y * 3 + 3):
                    for j in range(box_x * 3, box_x * 3 + 3):
                        if board[i][j] == num:
                            count += 1
                        if(count > 1): #if a number appears more than one time in a box 3x3
                            return False
                if count < 1: #if a number doesn't appear in a box
                    return False
    return True

# Esempio di utilizzo
sudoku_board = """
37. 5....6
... 36. .12
... .91 75.
... 154 .7.
..3 .7. 6..
.5. 638 ...
.64 98. ...
59. .26 ...
2.. ..5 .64
"""

board = parse_board(sudoku_board)
print("Sudoku iniziale:")
print_board(board)

if solve_sudoku(board):
    print("\nSoluzione:")
    print_board(board)
else:
    print("\nNessuna soluzione trovata.")

# Verifica la validità della soluzione
def is_solution_valid(board):
    # Verifica righe e colonne
    for i in range(9):
        if len(set(board[i])) != 9 or len(set(board[:, i])) != 9:
            return False
    
    # Verifica box 3x3
    for i in range(0, 9, 3):
        for j in range(0, 9, 3):
            if len(set(board[i:i+3, j:j+3].flatten())) != 9:
                return False
    
    return True

print("\nLa soluzione è valida:", is_solution_valid(board), board_is_solved(board))

Sudoku iniziale:
3 7 0 | 5 0 0 | 0 0 6
0 0 0 | 3 6 0 | 0 1 2
0 0 0 | 0 9 1 | 7 5 0
- - - - - - - - - - - -
0 0 0 | 1 5 4 | 0 7 0
0 0 3 | 0 7 0 | 6 0 0
0 5 0 | 6 3 8 | 0 0 0
- - - - - - - - - - - -
0 6 4 | 9 8 0 | 0 0 0
5 9 0 | 0 2 6 | 0 0 0
2 0 0 | 0 0 5 | 0 6 4

Soluzione:
3 7 1 | 5 4 2 | 8 9 6
9 8 5 | 3 6 7 | 4 1 2
6 4 2 | 8 9 1 | 7 5 3
- - - - - - - - - - - -
8 2 6 | 1 5 4 | 3 7 9
4 1 3 | 2 7 9 | 6 8 5
7 5 9 | 6 3 8 | 2 4 1
- - - - - - - - - - - -
1 6 4 | 9 8 3 | 5 2 7
5 9 7 | 4 2 6 | 1 3 8
2 3 8 | 7 1 5 | 9 6 4

La soluzione è valida: True True


In [4]:
def solve_n_queens(n):
    def is_safe(board, row, col):
        # Controlla la riga
        for i in range(col):
            if board[row][i] == 1:
                return False
        
        # Controlla la diagonale superiore sinistra
        for i, j in zip(range(row, -1, -1), range(col, -1, -1)):
            if board[i][j] == 1:
                return False
        
        # Controlla la diagonale inferiore sinistra
        for i, j in zip(range(row, n, 1), range(col, -1, -1)):
            if board[i][j] == 1:
                return False
        
        return True

    def solve(board, col):
        if col >= n:
            return True
        
        for i in range(n):
            if is_safe(board, i, col):
                board[i][col] = 1
                if solve(board, col + 1):
                    return True
                board[i][col] = 0
        
        return False

    board = [[0 for _ in range(n)] for _ in range(n)]
    
    if solve(board, 0):
        return board
    else:
        return None

# Esempio di utilizzo
solution = solve_n_queens(8)
if solution:
    for row in solution:
        print(" ".join("X" if x else "0" for x in row))
else:
    print("Nessuna soluzione trovata.")

X 0 0 0 0 0 0 0
0 0 0 0 0 0 X 0
0 0 0 0 X 0 0 0
0 0 0 0 0 0 0 X
0 X 0 0 0 0 0 0
0 0 0 X 0 0 0 0
0 0 0 0 0 X 0 0
0 0 X 0 0 0 0 0


In [7]:
import numpy as np
from scipy.optimize import minimize

def objective(x):
    board = x.reshape(8, 8)
    
    # Penalizza valori non binari
    binary_penalty = np.sum((board * (1 - board))**2)
    
    # Penalizza più di una regina per riga/colonna
    row_penalty = np.sum((np.sum(board, axis=1) - 1)**2)
    col_penalty = np.sum((np.sum(board, axis=0) - 1)**2)
    
    # Penalizza regine sulla stessa diagonale
    diag_penalty = 0
    for i in range(-7, 8):
        diag_sum = np.sum(np.diag(board, k=i))
        diag_penalty += diag_sum * (diag_sum - 1)
    
    anti_diag_penalty = 0
    for i in range(-7, 8):
        anti_diag_sum = np.sum(np.diag(np.fliplr(board), k=i))
        anti_diag_penalty += anti_diag_sum * (anti_diag_sum - 1)
    
    return binary_penalty + row_penalty + col_penalty + diag_penalty + anti_diag_penalty

# Vincoli per mantenere i valori tra 0 e 1
bounds = [(0, 1) for _ in range(64)]

# Inizializzazione casuale
x0 = np.random.rand(64)

# Ottimizzazione
result = minimize(objective, x0, method='trust-constr', bounds=bounds)

# Arrotondamento del risultato
final_board = np.round(result.x.reshape(8, 8))

print("Soluzione trovata:")
print(final_board)
print("Valore della funzione obiettivo:", objective(result.x))

# Verifica se la soluzione è valida
if np.sum(final_board) == 8 and objective(final_board.flatten()) < 1e-6:
    print("Soluzione valida trovata!")
else:
    print("La soluzione non è completamente valida.")

Soluzione trovata:
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
Valore della funzione obiettivo: -5.232483501985244
La soluzione non è completamente valida.
